apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web-deployment
  labels:
    app: test-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:

      ### Resource Request GPU
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      ###

      # # ### Best-effort Spot Pod
      # terminationGracePeriodSeconds: 25
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: cloud.google.com/gke-spot
      #           operator: In
      #           values:
      #           - "true"
      # ###

      containers:
      - name: test-web
        #image: asia-northeast1-docker.pkg.dev/project-yhori/gke-tutorial-repo/test-web-image:latest
        image: asia-northeast1-docker.pkg.dev/project-yhori/gke-tutorial-repo/test-web-image:COMMIT_SHA

        # ### Resource Request CPU
        # resources:
        #   requests:
        #     cpu: 250m
        #     memory: 1Gi
        # ###

        ### Resource Request GPU
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: "2"
            memory: "2Gi"
        ###

        ports:
        - containerPort: 80